[project]
name = "sigbot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "colorama==0.4.6",
    "eli5==0.16.0",
    "numpy==2.3.4",
    "pandas==2.3.3",
    "python-binance==1.0.16",
    "python-dotenv==0.20.0",
    "matplotlib==3.10.7",
    "mplfinance==0.12.9b1",
    "python-telegram-bot==21.1",
    "proplot==0.9.5",
    "requests~=2.28.1",
    "tqdm==4.64.1",
    "pybit==5.6.2",
    "joblib>=1.3.0",
    "lightgbm>=4.4.0",
    "scikit-learn==1.6.0",
    "loguru==0.7.3",
    "seaborn==0.13.2",
    "TA-Lib==0.6.8",
    "scipy",
    "optuna==4.9.0",
    "icecream==2.2.0",
    "shap-hypetune==0.2.7",
    "setuptools<81",
]

[project.optional-dependencies]
dev = [
    "pytest==7.1.2",
    "pytest-mock==3.12.0",
    "freezegun==1.2.2",
    "black",
    "isort",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["api", "bot", "config", "data", "indicators", "log", "ml", "signal_stat", "signals", "telegram_api"]

[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/build/
^/dist/
^/\.eggs/
^/\.git/
^/\.hg/
^/\.mypy_cache/
^/\.nox/
^/\.tox/
^/\.venv/
^/venv/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [
    ".git",
    ".eggs",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".tox",
    ".venv",
    "venv",
    "build",
    "dist"
]

[tool.pytest.ini_options]
testpaths = ["./tests/"]
filterwarnings = ["ignore::DeprecationWarning", "ignore:Support for class-based"]
